# Base configs
baseurl: "https://www.marsliao.com"

google_analytics: "G-3106ZL9QWK"

# UI configs
title: "Design by Mars Liao"
# subtitle: "See the world through my eyes!"
author: "Mars Liao"
header:
 title: "Design"
 subtitle: "by Mars Liao"
footer:
 name: "Hey there, my name is Mars"
 bio: "I am a fashion design student in London College of Fashion"
 github: ""
social_urls:
  # facebook: "https://www.facebook.com/marliao"
  # twitter: "https://www.twitter.com/marliao"
  instagram: "https://www.instagram.com/marsliao_official/"
  # dribbble: "https://dribbble.com/marliao"
  # linkedin: "https://in.linkedin.com/in/marliao"
  # github: "https://www.github.com/mar-liao"

home_fulls_loc: "/images/home/fulls"
home_thumbs_loc: "/images/home/thumbs"