# Base configs
baseurl: "https://marsliao.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Design by Mars Liao"
subtitle: "See the world through my eyes!"
author: "Mars Liao"
header:
 title: "Design"
 subtitle: "by Mars Liao"
footer:
 name: "Hey there, my name is Mars"
 bio: "I am a beginner of fashion design"
 github: ""
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/marsliao_official/"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
